export enum ActionTypes {
  JOIN_SERVER = 'JOIN_SERVER',
  JOIN_ROOM = 'JOIN_ROOM',
  CREATE_ROOM = 'CREATE_ROOM',
  ROOM_CREATED = 'ROOM_CREATED',
  UPDATE_USER = 'UPDATE_USER',
  MESSAGE = 'MESSAGE',
  SEND_MESSAGE = 'SEND_MESSAGE',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_SENT = 'MESSAGE_SENT',
}
