export enum EventTypes {
  ROOM_CREATED = 'ROOM_CREATED',
  MESSAGE = 'MESSAGE',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE',
  JOIN_ROOM = 'JOIN_ROOM',
  ROOM_DATA = 'ROOM_DATA',
}
